name = "QuAlgorithmZoo"
uuid = "65c24e16-9b0a-11e8-1353-efc5bc5f6586"
authors = ["Roger-luo <hiroger@qq.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LuxurySparse = "d05aeea4-b7d4-55ac-b691-9e7fabb07ba2"
Yao = "1bc31baa-972f-11e8-31dd-c182aaa973df"
