name = "YaoBlockTree"
uuid = "9ef32aa8-2a2b-11e9-20a5-91815742e9ae"
authors = ["Roger-luo <hiroger@qq.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
